//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace HeatKeeper.Server.EnergyPrices {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:3")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:3", IsNullable=false)]
    public partial class Publication_MarketDocument {
        
        private string mRIDField;
        
        private string revisionNumberField;
        
        private string typeField;
        
        private PartyID_String sender_MarketParticipantmRIDField;
        
        private string sender_MarketParticipantmarketRoletypeField;
        
        private PartyID_String receiver_MarketParticipantmRIDField;
        
        private string receiver_MarketParticipantmarketRoletypeField;
        
        private System.DateTime createdDateTimeField;
        
        private ESMP_DateTimeInterval periodtimeIntervalField;
        
        private AreaID_String domainmRIDField;
        
        private Action_Status docStatusField;
        
        private TimeSeries[] timeSeriesField;
        
        /// <remarks/>
        public string mRID {
            get {
                return this.mRIDField;
            }
            set {
                this.mRIDField = value;
            }
        }
        
        /// <remarks/>
        public string revisionNumber {
            get {
                return this.revisionNumberField;
            }
            set {
                this.revisionNumberField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sender_MarketParticipant.mRID")]
        public PartyID_String sender_MarketParticipantmRID {
            get {
                return this.sender_MarketParticipantmRIDField;
            }
            set {
                this.sender_MarketParticipantmRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sender_MarketParticipant.marketRole.type")]
        public string sender_MarketParticipantmarketRoletype {
            get {
                return this.sender_MarketParticipantmarketRoletypeField;
            }
            set {
                this.sender_MarketParticipantmarketRoletypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("receiver_MarketParticipant.mRID")]
        public PartyID_String receiver_MarketParticipantmRID {
            get {
                return this.receiver_MarketParticipantmRIDField;
            }
            set {
                this.receiver_MarketParticipantmRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("receiver_MarketParticipant.marketRole.type")]
        public string receiver_MarketParticipantmarketRoletype {
            get {
                return this.receiver_MarketParticipantmarketRoletypeField;
            }
            set {
                this.receiver_MarketParticipantmarketRoletypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createdDateTime {
            get {
                return this.createdDateTimeField;
            }
            set {
                this.createdDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("period.timeInterval")]
        public ESMP_DateTimeInterval periodtimeInterval {
            get {
                return this.periodtimeIntervalField;
            }
            set {
                this.periodtimeIntervalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("domain.mRID")]
        public AreaID_String domainmRID {
            get {
                return this.domainmRIDField;
            }
            set {
                this.domainmRIDField = value;
            }
        }
        
        /// <remarks/>
        public Action_Status docStatus {
            get {
                return this.docStatusField;
            }
            set {
                this.docStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TimeSeries")]
        public TimeSeries[] TimeSeries {
            get {
                return this.timeSeriesField;
            }
            set {
                this.timeSeriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:3")]
    public partial class PartyID_String {
        
        private string codingSchemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codingScheme {
            get {
                return this.codingSchemeField;
            }
            set {
                this.codingSchemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:3")]
    public partial class Winners_MarketParticipant {
        
        private PartyID_String mRIDField;
        
        /// <remarks/>
        public PartyID_String mRID {
            get {
                return this.mRIDField;
            }
            set {
                this.mRIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:3")]
    public partial class Reason {
        
        private string codeField;
        
        private string textField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:3")]
    public partial class Point {
        
        private string positionField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal priceamountField;
        
        private bool priceamountFieldSpecified;
        
        private Reason[] reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public decimal quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("price.amount")]
        public decimal priceamount {
            get {
                return this.priceamountField;
            }
            set {
                this.priceamountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceamountSpecified {
            get {
                return this.priceamountFieldSpecified;
            }
            set {
                this.priceamountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reason")]
        public Reason[] Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:3")]
    public partial class Series_Period {
        
        private ESMP_DateTimeInterval timeIntervalField;
        
        private string resolutionField;
        
        private Point[] pointField;
        
        /// <remarks/>
        public ESMP_DateTimeInterval timeInterval {
            get {
                return this.timeIntervalField;
            }
            set {
                this.timeIntervalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string resolution {
            get {
                return this.resolutionField;
            }
            set {
                this.resolutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Point")]
        public Point[] Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:3")]
    public partial class ESMP_DateTimeInterval {
        
        private string startField;
        
        private string endField;
        
        /// <remarks/>
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:3")]
    public partial class ResourceID_String {
        
        private string codingSchemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codingScheme {
            get {
                return this.codingSchemeField;
            }
            set {
                this.codingSchemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:3")]
    public partial class TimeSeries {
        
        private string mRIDField;
        
        private string auctionmRIDField;
        
        private string auctiontypeField;
        
        private string auctioncategoryField;
        
        private string businessTypeField;
        
        private AreaID_String in_DomainmRIDField;
        
        private AreaID_String out_DomainmRIDField;
        
        private string contract_MarketAgreementtypeField;
        
        private string quantity_Measure_UnitnameField;
        
        private string currency_UnitnameField;
        
        private string price_Measure_UnitnameField;
        
        private string classificationSequence_AttributeInstanceComponentpositionField;
        
        private string participantNumber_AttributeInstanceComponentpositionField;
        
        private string winnerParticipantNumber_AttributeInstanceComponentpositionField;
        
        private string curveTypeField;
        
        private System.DateTime update_DateAndOrTimedateTimeField;
        
        private bool update_DateAndOrTimedateTimeFieldSpecified;
        
        private ResourceID_String connectingLine_RegisteredResourcemRIDField;
        
        private Series_Period[] periodField;
        
        private Reason[] reasonField;
        
        private Winners_MarketParticipant[] winners_MarketParticipantField;
        
        /// <remarks/>
        public string mRID {
            get {
                return this.mRIDField;
            }
            set {
                this.mRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("auction.mRID")]
        public string auctionmRID {
            get {
                return this.auctionmRIDField;
            }
            set {
                this.auctionmRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("auction.type")]
        public string auctiontype {
            get {
                return this.auctiontypeField;
            }
            set {
                this.auctiontypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("auction.category")]
        public string auctioncategory {
            get {
                return this.auctioncategoryField;
            }
            set {
                this.auctioncategoryField = value;
            }
        }
        
        /// <remarks/>
        public string businessType {
            get {
                return this.businessTypeField;
            }
            set {
                this.businessTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("in_Domain.mRID")]
        public AreaID_String in_DomainmRID {
            get {
                return this.in_DomainmRIDField;
            }
            set {
                this.in_DomainmRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("out_Domain.mRID")]
        public AreaID_String out_DomainmRID {
            get {
                return this.out_DomainmRIDField;
            }
            set {
                this.out_DomainmRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contract_MarketAgreement.type")]
        public string contract_MarketAgreementtype {
            get {
                return this.contract_MarketAgreementtypeField;
            }
            set {
                this.contract_MarketAgreementtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("quantity_Measure_Unit.name")]
        public string quantity_Measure_Unitname {
            get {
                return this.quantity_Measure_UnitnameField;
            }
            set {
                this.quantity_Measure_UnitnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("currency_Unit.name")]
        public string currency_Unitname {
            get {
                return this.currency_UnitnameField;
            }
            set {
                this.currency_UnitnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("price_Measure_Unit.name")]
        public string price_Measure_Unitname {
            get {
                return this.price_Measure_UnitnameField;
            }
            set {
                this.price_Measure_UnitnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classificationSequence_AttributeInstanceComponent.position", DataType="integer")]
        public string classificationSequence_AttributeInstanceComponentposition {
            get {
                return this.classificationSequence_AttributeInstanceComponentpositionField;
            }
            set {
                this.classificationSequence_AttributeInstanceComponentpositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("participantNumber_AttributeInstanceComponent.position", DataType="integer")]
        public string participantNumber_AttributeInstanceComponentposition {
            get {
                return this.participantNumber_AttributeInstanceComponentpositionField;
            }
            set {
                this.participantNumber_AttributeInstanceComponentpositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("winnerParticipantNumber_AttributeInstanceComponent.position", DataType="integer")]
        public string winnerParticipantNumber_AttributeInstanceComponentposition {
            get {
                return this.winnerParticipantNumber_AttributeInstanceComponentpositionField;
            }
            set {
                this.winnerParticipantNumber_AttributeInstanceComponentpositionField = value;
            }
        }
        
        /// <remarks/>
        public string curveType {
            get {
                return this.curveTypeField;
            }
            set {
                this.curveTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("update_DateAndOrTime.dateTime")]
        public System.DateTime update_DateAndOrTimedateTime {
            get {
                return this.update_DateAndOrTimedateTimeField;
            }
            set {
                this.update_DateAndOrTimedateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool update_DateAndOrTimedateTimeSpecified {
            get {
                return this.update_DateAndOrTimedateTimeFieldSpecified;
            }
            set {
                this.update_DateAndOrTimedateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("connectingLine_RegisteredResource.mRID")]
        public ResourceID_String connectingLine_RegisteredResourcemRID {
            get {
                return this.connectingLine_RegisteredResourcemRIDField;
            }
            set {
                this.connectingLine_RegisteredResourcemRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Period")]
        public Series_Period[] Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reason")]
        public Reason[] Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Winners_MarketParticipant")]
        public Winners_MarketParticipant[] Winners_MarketParticipant {
            get {
                return this.winners_MarketParticipantField;
            }
            set {
                this.winners_MarketParticipantField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:3")]
    public partial class AreaID_String {
        
        private string codingSchemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codingScheme {
            get {
                return this.codingSchemeField;
            }
            set {
                this.codingSchemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:3")]
    public partial class Action_Status {
        
        private string valueField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
