language: csharp
mono: none
dotnet: 2.2.100
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
matrix:
  include:
    - os: linux
      dist: trusty
script:
  - chmod +x build.sh
  - ./build.sh
