version: "3"
services:
  heatkeeper:
    image: bernhardrichter/heatkeeper:0.5.0
    container_name: heatkeeper
    volumes:
      - sqlite-volume:/db
    environment:
      - "HEATKEEPER_SECRET=${HEATKEEPER_SECRET}"    
      - "HEATKEEPER_MQTT_BROKER_ADDRESS=${HEATKEEPER_MQTT_BROKER_ADDRESS}"
      - "HEATKEEPER_MQTT_BROKER_USER=${HEATKEEPER_MQTT_BROKER_USER}"
      - "HEATKEEPER_MQTT_BROKER_PASSWORD=${HEATKEEPER_MQTT_BROKER_PASSWORD}"
      - "HEATKEEPER_CHANNELSTATE_CRONEXPRESSION=${HEATKEEPER_CHANNELSTATE_CRONEXPRESSION}"
    ports:
      - "5000:80"

  heatkeeper-reporter:
    image: heatkeeper.reporter.osx:latest
    container_name: heatkeeper-reporter
    volumes:
      - ./reportertest/reporter.csx:/reporter.csx
    command: reporter.csx

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-volume:/var/lib/grafana
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --debug
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./mosquitto/log/:/mosquitto/log/
      - mosquitto-volume:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
volumes:
  grafana-volume:
  influxdb-volume:
  sqlite-volume:
  mosquitto-volume:
