version: '3'
services:
  influxdb:
    image: influxdb:2.6.1
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=secret-password
      - DOCKER_INFLUXDB_INIT_ORG=my-init-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-init-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secret-token
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./db/influxdb/data:/var/lib/influxdb2
      - ./db/influxdb/config:/etc/influxdb2
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./db/grafana/data:/var/lib/grafana
