services:
 
  grafana:
    image: grafana/grafana:latest    
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./db/grafana/data:/var/lib/grafana
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./mosquitto/log/:/mosquitto/log/
      - mosquitto_data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  mosquitto_data: ~
