version: "3"
services:
  heatkeeper:
    image: bernhardrichter/heatkeeper:latest
    container_name: heatkeeper
    volumes:
      - ./db/sqlite/data:/heatkeeper/db
    environment:
      - "secret=${secret}"
    ports:
      - "5000:80"
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./db/influxdb/data:/var/lib/influxdb
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --debug
