version: "3"
services:
  heatkeeper:
    image: bernhardrichter/heatkeeper:0.0.6
    container_name: heatkeeper
    volumes:
      - sqlite-volume:/db
    environment:
      - "HEATKEEPER_SECRET=${HEATKEEPER_SECRET}"
    ports:
      - "5000:80"
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb:2.6.1
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=heatkeeper
      - DOCKER_INFLUXDB_INIT_PASSWORD=heatkeeper-password
      - DOCKER_INFLUXDB_INIT_ORG=heatkeeper
      - DOCKER_INFLUXDB_INIT_BUCKET=default-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=heatkeeper-admin-token
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-volume:/var/lib/influxdb2
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --debug
volumes:
  grafana-volume:
  influxdb-volume:
  sqlite-volume:
