version: '3'
services:
  heatkeeper:
    build: .
    image: seesharper/heatkeeper
    container_name: heatkeeper
    volumes:
      - ./db/sqlite/data:/heatkeeper/db
    environment:
      - "secret=${secret}"
    ports:
      - "5000:80"
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
       - ./db/influxdb/data:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./db/grafana/data:/var/lib/grafana
  chronograf:
    image: chronograf:latest
    entrypoint: 'chronograf --influxdb-url=http://influxdb:8086'
    depends_on:
      - influxdb
    container_name: chronograf
    ports: ['8888:8888']
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro