POST https://localhost:7167/api/users/authenticate
content-type: application/json

{
    "email": "admin@no.org",
    "password": "Admin-1234"
}


###
GET https://heatkeeper.no/api/locations

###
POST https://localhost:7167/api/energy-prices/import
content-type: application/json

{
    "DateToImport": "2024-12-26"
}

###
POST http://localhost:5000/api/measurements
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiRmlyc3QgbmFtZSIsImZhbWlseV9uYW1lIjoiTGFzdCBOYW1lIiwiZW1haWwiOiJhZG1pbkBuby5vcmciLCJyb2xlIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIxIiwibmJmIjoxNTg5Mjg3MDg4LCJleHAiOjE1ODk4OTE4ODgsImlhdCI6MTU4OTI4NzA4OH0.v_HMb3mKTJ9rJ86h6Fyetl3vdQ9vArjyT5C-bNUNabE
content-type: application/json


[
    {
    "measurementType": 1,
    "value" : 23,
    "sensorid": "Testsensor"
    }
]


